Change category subject about "announcements" for restrictions
mdn/mdn-community pull request #224
Opened 2022-09-03 22:09 UTC by softorangetech200

There **is** a restriction to the announcements category. If I open a discussion, it doesn't show Announcements.

2022-09-06 13:53 UTC, Rumyra requested changes

2022-09-06 13:53 UTC, Rumyra commented on README.md
> +| 📣  [Announcements](https://github.com/mdn/mdn-community/discussions/categories/announcements) | This category is reserved for MDN Web Docs staff. There are restrictions in place to prevent others f
```suggestion
| 📣  [Announcements](https://github.com/mdn/mdn-community/discussions/categories/announcements) | This category is reserved for MDN Web Docs staff to make any announcements in relation to the MDN project |
```

2022-09-06 13:53 UTC, Rumyra commented
Hi @softorangetech200 - thanks for the contribution.

You are correct - this category is locked. However I suggested a change as I don't think it needs a mention, just more explicit text for the category 👍

2022-09-07 07:33 UTC, bsmth approved these changes
Looks good 👍🏻

2022-09-07 07:34 UTC, merged