Update README.md
mdn/mdn-community pull request #59
Opened 2022-04-30 16:05 UTC by schalkneethling

Minor update to README

2022-05-01 22:35 UTC, dipikabh requested changes
Thanks for your work on updating this page, @schalkneethling! Leaving a few suggestions for your consideration. Let me know what you think.

2022-05-01 22:35 UTC, dipikabh commented on README.md
> +We put people first and do our best to recognize, appreciate and respect the diversity of our global contributors. The MDN Web Docs project welcomes contributions from everyone who shares our goals a
How about something along the lines of: 
```suggestion
Welcome to the MDN Web Docs project! We are delighted with your interest in this project.

At MDN, we put people first and do our best to recognize, appreciate, and respect the diversity of our global contributors. We welcome contributions from everyone who shares our goals and wants to contribute healthily, respectfully, and constructively to this project.
```

2022-05-01 22:35 UTC, dipikabh commented on README.md
> +MDN community is the repository where you will find the official MDN Web Docs [public feedback discussions](https://github.com/mdn/mdn-community/discussions). By participating in and contributing to,
```suggestion
`mdn-community` is the repository where you will find the [public feedback discussions](https://github.com/mdn/mdn-community/discussions) for the MDN Web Docs project.

> **Note:** By participating in and contributing to our projects and discussions, you acknowledge that you have read and agree to the [Mozilla community participation guidelines](https://github.com/mdn/mdn-community/blob/main/CODE_OF_CONDUCT.md).
```

2022-05-02 13:08 UTC, schalkneethling commented
Thanks, @dipikabh, committed your suggestions.

2022-05-04 13:46 UTC, dipikabh commented on README.md
> +# mdn-communtiy
```suggestion
# mdn-community
```

2022-05-04 21:16 UTC, dipikabh approved these changes

2022-05-04 21:16 UTC, merged