Update README.md
mdn/mdn-community pull request #68
Opened 2022-05-10 15:05 UTC by schalkneethling

Adds a table with a detailed explanation of the intent of each category.

2022-05-10 17:09 UTC, dipikabh requested changes
Thanks @schalkneethling for this important addition! 👍 

Is it in any way possible to have this table right on the [discussions](https://github.com/mdn/mdn-community/discussions) page? (also this readme is getting too long with a lot of important messages). It might be more efficient to have the table on the discussions page to avoid toggling with this page to see the definitions.
Better still, can each category on the discussions page have a statement describing the intent of the category - that will make the contributors stop and think if they're in the right place even if they've missed to check this table of definitions.

2022-05-10 17:43 UTC, schalkneethling commented
> It might be more efficient to have the table on the discussions page to avoid toggling with this page to see the definitions.

That is unfortunately not possible at the moment.

2022-05-10 17:48 UTC, schalkneethling commented on README.md
> +| 🛠️  [Platform](https://github.com/mdn/mdn-community/discussions/categories/platform) | Discussions related to the [core](https://github.com/mdn/yari) MDN Web Docs platform. These discussions are me
> I guess 'discovery and exploration' part is applicable to all discussions?

Sure but here I wanted to call that out to make it clear it is not for bug reports.

2022-05-10 17:50 UTC, schalkneethling commented on README.md
> +- If the issue needs a discussion to agree upon a course of action or define an actionable piece of work, you are in the right place.
How about:

```suggestion
- If the issue needs a discussion to agree upon a course of action or to define an actionable piece of work, you are in the right place to initiate a discussion.
```

2022-05-10 17:51 UTC, schalkneethling commented on README.md
> +| **Feedback Category** | **Category subject** 	|
```suggestion
| **Discussion category** | **Category subject** 	|
```

2022-05-10 17:52 UTC, schalkneethling commented on README.md
> +| 🙋  [Content suggestions](https://github.com/mdn/mdn-community/discussions/categories/content-suggestions) | If you have an idea for new or improvements to existing content on MDN Web Docs, this is
Yeah, we will label some of the discussions. This is one of those we might label as such.

2022-05-10 17:57 UTC, schalkneethling commented
> can each category on the discussions page have a statement describing the intent of the category

You can have short blurbs, but nothing as long as we have here. I believe the intent is to have a place to point people to should we need to clarify. If people end up reading it beforehand, that is a bonus. Once this is merged, we can post an announcement and pin it to the discussions page.

Something like, "Please read this before starting a discussion" as the subject line.

2022-05-11 09:36 UTC, dipikabh commented on README.md
> +- If the issue needs a discussion to agree upon a course of action or define an actionable piece of work, you are in the right place.
Looks good

2022-05-11 09:37 UTC, dipikabh approved these changes

2022-05-11 09:38 UTC, merged